### ISSUE TITLE
Problems with logs directory

### ISSUE THREAD

**Issue by flopezag** [flopezag/fiware-management-scripts#1]
If the directory logs does not exist inside the folder DesksReminder and HelpDesk the scripts produce an error:

Traceback (most recent call last):
  File "/home/fla/fiware-management-scripts/DesksReminder/fiware-urgentDesk-weekly.py", line 24, in <module>
    level=log_level)
  File "/usr/lib/python2.7/logging/__init__.py", line 1532, in basicConfig
    hdlr = FileHandler(filename, mode)
  File "/usr/lib/python2.7/logging/__init__.py", line 903, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python2.7/logging/__init__.py", line 928, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 2] No such file or directory: '/home/fla/fiware-management-scripts/DesksReminder/logs/urgentdesk-weekly.log'

**Comment by flopezag** [comment]
It should be resolved with the installation of release 1.2.0
