### ISSUE TITLE
Problems in the execution of the account-desk.py

### ISSUE THREAD

**Issue by flopezag** [flopezag/fiware-management-scripts#14]
2017-04-27 08:33:08|ERROR:{u'smartsdk_martel': (553, '5.1.2 The recipient address <smartsdk_martel> is not a valid RFC-5321\n5.1.2 addre
ss. e12sm1162681wrc.43 - gsmtp')}
Traceback (most recent call last):
  File "/home/fla/fiware-management-scripts/DesksReminder/Basics/emailer.py", line 147, in _deliver
    server.sendmail(self._sender, msg['To'], msg.as_string())
  File "/usr/lib/python2.7/smtplib.py", line 747, in sendmail
    raise SMTPRecipientsRefused(senderrs)
SMTPRecipientsRefused: {u'smartsdk_martel': (553, '5.1.2 The recipient address <smartsdk_martel> is not a valid RFC-5321\n5.1.2 address.
 e12sm1162681wrc.43 - gsmtp')}

**Comment by flopezag** [comment]
The problem is due to they are not providing a correct email in the Jira account. It is resolved in Jira.
