### ISSUE TITLE
Connection unexpectedly closed

### ISSUE THREAD

**Issue by flopezag** [flopezag/fiware-management-scripts#3]
In some cases, the connection of the SMTP is closed unexpectly giving us the following information:

2017-01-17 13:23:22|ERROR:[-] Sending Mail Failed.
Traceback (most recent call last):
  File "/home/fla/fiware-management-scripts/DesksReminder/Basics/emailer.py", line 147, in _deliver
    server.sendmail(self._sender, msg['To'], msg.as_string())
  File "/usr/lib/python2.7/smtplib.py", line 723, in sendmail
    self.ehlo_or_helo_if_needed()
  File "/usr/lib/python2.7/smtplib.py", line 543, in ehlo_or_helo_if_needed
    (code, resp) = self.helo()
  File "/usr/lib/python2.7/smtplib.py", line 403, in helo
    (code, msg) = self.getreply()
  File "/usr/lib/python2.7/smtplib.py", line 368, in getreply
    raise SMTPServerDisconnected("Connection unexpectedly closed")
SMTPServerDisconnected: Connection unexpectedly closed

Not sure if it is a problem with the data or a problem with de code.

**Comment by flopezag** [comment]
I see it in the delivery_board.log

**Comment by flopezag** [comment]
From urgentdesk-weekly.log 

2018-01-15 06:50:23|ERROR:Connection unexpectedly closed
Traceback (most recent call last):
  File "/home/fla/fiware-management-scripts/DesksReminder/Basics/emailer.py", line 147, in _deliver
    server.sendmail(self._sender, msg['To'], msg.as_string())
  File "/usr/lib/python2.7/smtplib.py", line 723, in sendmail
    self.ehlo_or_helo_if_needed()
  File "/usr/lib/python2.7/smtplib.py", line 543, in ehlo_or_helo_if_needed
    (code, resp) = self.helo()
  File "/usr/lib/python2.7/smtplib.py", line 403, in helo
    (code, msg) = self.getreply()
  File "/usr/lib/python2.7/smtplib.py", line 368, in getreply
    raise SMTPServerDisconnected("Connection unexpectedly closed")
SMTPServerDisconnected: Connection unexpectedly closed
2018-01-15 06:50:23|ERROR:[-] Sending Mail Failed.
Traceback (most recent call last):
  File "/home/fla/fiware-management-scripts/DesksReminder/Basics/emailer.py", line 147, in _deliver
    server.sendmail(self._sender, msg['To'], msg.as_string())
  File "/usr/lib/python2.7/smtplib.py", line 723, in sendmail
    self.ehlo_or_helo_if_needed()
  File "/usr/lib/python2.7/smtplib.py", line 543, in ehlo_or_helo_if_needed
    (code, resp) = self.helo()
  File "/usr/lib/python2.7/smtplib.py", line 403, in helo
    (code, msg) = self.getreply()
  File "/usr/lib/python2.7/smtplib.py", line 368, in getreply
    raise SMTPServerDisconnected("Connection unexpectedly closed")
SMTPServerDisconnected: Connection unexpectedly closed
